### ISSUE TITLE
System should be handle data from various file sources (local disk, FTP site, online download, etc)

### ISSUE THREAD

**Issue by daniellu** [HatfieldConsultants/Hatfield.EnviroData.DataAcquisition#15]

**Comment by daniellu** [comment]
Local File System support added at https://github.com/daniellu/Hatfield.EnviroData.DataAcquisition/commit/9db465b89627a41d672d621cc93705ba784c52b5

**Comment by kgarsuta** [comment]
How would you like to hand credentials for FtpFileSystem? The constructor or IFileSystem.FetchData() takes no parameters.

**Comment by jsuwala** [comment]
Kyle: There should be a way for an end-user to specify the credentials 
(through some sort of configuration interface – either a web UI or a 
configuration file) that is then passed to the FtpFileSystem instance. 
Perhaps a Dictionary<string,string> should be added to IFileSystem to allow 
these custom configuration parameters to be passed in.



Best regards,

- Jason

**Comment by kgarsuta** [comment]
437a0d05c21a098d9b6194a23ddc9becb7a07509

**Comment by daniellu** [comment]
Issue closed. All file system related issues are moved to the FileSystems project.
